platform :ios, '10.2'

target 'BubbleMania' do
  use_frameworks!

  # Pods for BubbleMania
  pod 'PhysicsEngine', :git => "https://github.com/riwu/BubbleMania.git", :branch => "cocoapod", :tag => "1"
  target 'BubbleManiaTests' do
    inherit! :search_paths
  end

end
